version: '3.5'
services:
  nextjs:
    container_name: ambisius-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
